function setUpFigureWindow(obj)
    % Set up the measurePSF figure window by placing empty axes and
    % place-holder plot elements that will later be updated.
    %
    %
    % Rob Campbell, Basel Biozentrum, initial commit 2016

    obj.reportMethodEntry

    % Create a figure window
    obj.hFig = figure;
    obj.hFig.CloseRequestFcn = @obj.windowCloseFcn;

    obj.hFig.Position = [15,50,900,900];

    %Add plot axes and empty plot elements

    % The bottom/left plot showing a cross-section through maximum brightness region
    obj.hPSF_XYmidpointImageAx = axes('Position',[0.03,0.07,0.4,0.4]);
    obj.hPSF_XYmidpointImageIM = imagesc(obj.hPSF_XYmidpointImageAx, obj.maxZplane);

    %Add place-holder lines to the main X/Y plot showing where we are slicing it to take the cross-sections
    hold on
    obj.hPS_midPointImageXhairs(1)=plot(xlim,[0,0],'--w');
    obj.hPS_midPointImageXhairs(2)=plot([0,0],ylim,'--w');
    obj.hPSF_midPointText = text(0,0,'', 'color','w', 'VerticalAlignment','top');
    hold off


    %The cross-section sliced along the rows (the fit shown along the right side of the X/Y PSF)
    obj.hxSectionRowsAx = axes('Position',[0.435,0.07,0.1,0.4]);

    %The cross-section sliced down the columns (fit shown above the X/Y PSF)
    obj.hxSectionColsAx=axes('Position',[0.03,0.475,0.4,0.1]);

    %Axes for axial PSF cross-sections
    obj.hPSF_ZXax = axes('Position',[0.03,0.6,0.4,0.25]);
    text(1,1,sprintf('PSF in Z/X'), 'Color','w','VerticalAlignment','top');
    obj.hPSF_ZX_fitAx = axes('Position',[0.03,0.85,0.4,0.1]);

    obj.hPSF_ZYax=axes('Position',[0.56,0.07,0.25,0.4]);
    text(1,1,sprintf('PSF in Z/Y'), 'Color','w','VerticalAlignment','top');
    obj.hPSF_ZY_fitAx = axes('Position',[0.8,0.07,0.1,0.4]);


    % Add a plot with a scroll-bar so we can view the PSF as desires
    obj.hUserSelectedPlaneAx = axes('Position',[0.5,0.55,0.4,0.4]);
    obj.hUserSelectedPlaneIM = imagesc(obj.maxZplane);
    set(obj.hUserSelectedPlaneAx,'XTick',[],'YTick',[], 'Box', 'On')
    axis tight %Used for zooming to work nicely
    obj.hSlider = uicontrol('Style','Slider', ...
                        'Units','normalized',...
                        'Position',[0.9,0.55,0.02,0.4],...
                        'Min',1,...
                        'Max',size(obj.PSFstack,3),...
                        'Value',obj.psfCenterInZ,...
                        'Tag','DepthSlider');

    obj.listeners{end+1} = addlistener(obj.hSlider, 'Value', 'PreSet',@obj.updateUserSelected);

    obj.hUserSelectedPlaneTitle=title(sprintf('Slice #%d', obj.psfCenterInZ));


    % Add further UI elements
    obj.drawBox_PushButton = uicontrol('Style', 'PushButton', 'Units', 'Normalized', ...
                'Position', [0.025, 0.025, 0.10, 0.04], 'String', 'Select bead', ...
                'ToolTip', 'Manually select a sub-region of the image', ...
                'Callback', @obj.areaSelector);

    obj.reset_PushButton = uicontrol('Style', 'PushButton', 'Units', 'Normalized', ...
                'Position', [0.135, 0.025, 0.10, 0.04], 'String', 'Reset view', ...
                'ToolTip', 'Zoom out and reset view', ...
                'Callback', @obj.resetView);

    obj.fitToBaseWorkSpace_PushButton = uicontrol('Style', 'PushButton', 'Units', 'Normalized', ...
                'Position', [0.245, 0.025, 0.15, 0.04], 'String', 'PSF data to workspace', ...
                'ToolTip', 'Copy PSF parameters to the base workspace', ...
                'Callback', @obj.copyFitToBaseWorkSpace);

    obj.saveImage_PushButton = uicontrol('Style', 'PushButton', 'Units', 'Normalized', ...
                'Position', [0.4, 0.025, 0.15, 0.04], 'String', 'Save Image', ...
                'ToolTip', 'Save image to Desktop', ...
                'Callback', @obj.saveImage);


    obj.useMaxIntensityForZpsf_checkBox = uicontrol('Style', 'CheckBox', 'Units', 'Normalized', ...
                'Value', obj.useMaxIntensityForZpsf, ...
                'Position', [0.65, 0.001, 0.15, 0.025], 'String', 'Max Intensity for Z', ...
                'ToolTip', 'Use maximum intensity along axis for Z PSF', ...
                'Callback', @obj.maxIntCallback);

    % Median filter text and edit box pair
    obj.textMedian = uicontrol('Style', 'Text', 'Units', 'Normalized', ...
                'String', 'Median filter width', ...
                'Position', [0.67, 0.03, 0.1, 0.02]);
    obj.medFiltSize_editBox = uicontrol('Style', 'Edit', 'Units', 'Normalized', ...
                'String', num2str(obj.medFiltSize), ...
                'Position', [0.77, 0.03, 0.035, 0.02], ...
                'ToolTip', 'Median filter width', ...
                'Callback', @obj.medFiltSizeCallback);

    % Z fit order
    obj.textZfit = uicontrol('Style', 'Text', 'Units', 'Normalized', ...
                'String', 'Z fit order', ...
                'Position', [0.55, 0.03, 0.08, 0.02]);
    obj.zFitOrder_editBox = uicontrol('Style', 'Edit', 'Units', 'Normalized', ...
                'String', num2str(obj.zFitOrder), ...
                'Position', [0.63, 0.03, 0.035, 0.02], ...
                'ToolTip', 'Median filter width', ...
                'Callback', @obj.zFitOrderCallback);
end

